In [1]:
import numpy as np

# 18 Limit the number of items printed in python numpy array a to a maximum of 6 elements
arr13 = np.arange(15)
np.set_printoptions(threshold=6)
print(arr13)

[ 0  1  2 ... 12 13 14]


In [2]:
# Print or show only 3 decimal places of the numpy array rand_arr
rand_arr3 = np.random.uniform(5, 10, size=(5, 3))
np.set_printoptions(precision=3)
print(rand_arr3)

[[7.586 5.996 6.434]
 [7.952 5.691 6.951]
 [6.688 7.949 5.039]
 [7.363 7.432 8.313]
 [9.444 5.596 8.629]]


In [4]:
# Extract all odd numbers from arr
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3 = arr3[arr3 % 2 == 1]
arr3

array([1, 3, 5, 7, 9])

In [7]:
# 7 Stack arrays a and b vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# method 1
a_b_1 = np.concatenate([a, b], axis=0)
print(a_b_1)

# method 2
a_b_2 = np.vstack([b, a])
print(a_b_2)

# method 3
a_b_3 = np.r_[a, b]
print(a_b_3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
# Replace all odd numbers in arr with -1 without changing arr
arr5 = np.arange(10)
out = np.where(arr5 % 2 == 1, -1, arr5)
print(arr5)
print(out)

[0 1 2 ... 7 8 9]
[ 0 -1  2 ... -1  8 -1]


In [9]:
# 9 Create the following pattern without hardcoding. Use only numpy functions and the below input array a
# a = np.array([1,2,3])  #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1,
# 2, 3, 1, 2, 3])
a1 = np.array([1, 2, 3])
# b1 = np.r_[a1.repeat(3)]
# b1 = np.r_[np.tile(a1, 3)]
b1 = np.r_[np.repeat(a1, 3), np.tile(a1, 3)]
np.set_printoptions(threshold=30)
print(b1)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [10]:
# 10 Get the common items between a and b
a2 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6, 9])
b2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.intersect1d(a2, b2))

[2 4 9]


In [11]:
# 11 From array a remove all items present in array b
a3 = np.array([1, 2, 3, 4, 5, 6])
b3 = np.array([4, 5, 6, 7, 8, 9])
print(np.setdiff1d(a3, b3))
print(np.setdiff1d(b3, a3))

[1 2 3]
[7 8 9]


In [13]:
# 12 Get the positions where elements of a and b match,the same elements
a4 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b4 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.where(a4 == b4)

(array([1, 3, 5, 7], dtype=int64),)

In [14]:
# 13 Get all items between 5 and 10 from a
a5 = np.array([2, 6, 1, 9, 10, 3, 27])

# method 1
print(a5[np.where((a5 >= 5) & (a5 <= 10))])

# method 2
print(a5[(a5 >= 5) & (a5 <= 10)])

# method 3
print(a5[np.where(np.logical_and(a5 >= 5, a5 <= 10))])

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]
