# numpy中的矩阵和向量

numpy的ndarray类用于表示矩阵和向量。

要在numpy中构造矩阵，我们在列表中列出矩阵的行，并将该列表传递给numpy数组构造函数。

例如，构造与矩阵对应的numpy数组 $$\left\lgroup \matrix{1 & -1 & 2\cr 3 & 2 & 0} \right\rgroup$$

In [2]:
import numpy as np

In [4]:
A = np.array([[1,-1,2], [3,2,0]])
A

array([[ 1, -1,  2],
       [ 3,  2,  0]])

向量只是具有单列的数组; 例如，构建向量
$$\left\lgroup \matrix{2 \cr 1 \cr 3} \right\rgroup$$

In [9]:
B = np.array([[2], [1], [3]])
B

array([[2],
       [1],
       [3]])

将该矩阵转置：$$\lgroup \matrix{2,1,3} \rgroup $$

In [10]:
B_trans = np.transpose(B)
B_trans

array([[2, 1, 3]])

### 用numpy求解方程组
线性代数中比较常见的问题之一是求解矩阵向量方程, 我们寻找解决方程的向量x

A x = b

$A = \left\lgroup \matrix{2,1,-2\cr 3,0,1\cr 1,1,-1} \right\rgroup $

$B = \left\lgroup \matrix{-3\cr 5\cr 2} \right\rgroup $

In [14]:
A = np.array([[2, 1, -2], [3, 0, 1], [1, 1, -1]])
B = np.transpose(np.array([[-3, 5, 2]]))

x = np.linalg.solve(A, B)
x

array([[0.],
       [7.],
       [5.]])